### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by Takuzo01** [vita-epfl/CrowdNav#4]
Dear prof.Chen
I tried to run this command "python test.py --policy orca --phase test --visualize --test_case 4 --gpu "
,output "TypeError: 'NoneType' object is not subscriptable". I tried to repair but it didn't work. Any help is appreciated.
Thanks,
Taku 
################################################################################
Details: python test.py --policy orca --phase test --visualize --test_case 4 --gpu 
2018-10-10 10:22:17, INFO: Using device: cuda:0
hereconfigs/policy.config
configs/env.config
2018-10-10 10:22:17, INFO: human number: 5
2018-10-10 10:22:17, INFO: Not randomize human's radius and preferred speed
2018-10-10 10:22:17, INFO: Training simulation: circle_crossing, test simulation: circle_crossing
2018-10-10 10:22:17, INFO: Square width: 10.0, circle width: 4.0
2018-10-10 10:22:17, INFO: ORCA agent buffer: 0.000000
2018-10-10 10:22:17, INFO: Agent is invisible and has holonomic kinematic constraint
args.video_file None
5
Traceback (most recent call last):
  File "test.py", line 115, in <module>
    main()
  File "test.py", line 104, in main
    env.render('video', args.video_file)
  File /CrowdNav/crowd_sim/envs/crowd_sim.py", line 504, in render
    humans = [plt.Circle(human_positions[0][i], self.humans[i].radius,fill=False,color=(self.attention_weights[0][i], 0, 0)) for i in range(len(self.humans))]
  File "/CrowdNav/crowd_sim/envs/crowd_sim.py", line 504, in <listcomp>
    humans = [plt.Circle(human_positions[0][i], self.humans[i].radius,fill=False,color=(self.attention_weights[0][i], 0, 0)) for i in range(len(self.humans))]
TypeError: 'NoneType' object is not subscriptable

**Comment by ChanganVR** [comment]
Hi, thanks for your feedback. I have fixed the bug. And also this framework runs faster on CPU. So it's recommended to run without the --gpu flag.
