### ISSUE TITLE
training issues

### ISSUE THREAD

**Issue by yuansaimei** [vita-epfl/CrowdNav#43]
python test.py --policy sarl --model_dir data/output --phase test --visualize --test_case 0 --traj
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    from crowd_nav.utils.explorer import Explorer
  File "/home/ubuntu/J/TLSGAN-master/crowd_nav/utils/explorer.py", line 7, in <module>
    from crowd_nav.policy.policy_factory import policy_factory
  File "/home/ubuntu/J/TLSGAN-master/crowd_nav/policy/policy_factory.py", line 6, in <module>
    policy_factory['cadrl'] = CADRL
TypeError: 'module' object does not support item assignment

**Comment by ChanganVR** [comment]
I just did a clean install and training/testing. Everything worked just
fine. Please check if you modified any code that lead to this error.
