### ISSUE TITLE
training problem

### ISSUE THREAD

**Issue by naiyisiji** [vita-epfl/CrowdNav#45]
sorry to bother you.
Do you know how to deal with this error?

Traceback (most recent call last):
  File "/home/naiyisiji/Projects/CrowdNav/crowd_nav/train.py", line 177, in <module>
    main()
  File "/home/naiyisiji/Projects/CrowdNav/crowd_nav/train.py", line 129, in main
    explorer.run_k_episodes(il_episodes, 'train', update_memory=True, imitation_learning=True)
  File "/home/naiyisiji/Projects/CrowdNav/crowd_nav/utils/explorer.py", line 36, in run_k_episodes
    **ob = self.env.reset(phase)**
**TypeError: reset() takes 1 positional argument but 2 were given**

**Comment by HyeongYeolRyu** [comment]
Hi  @naiyisiji, I'm not the author, but I had encountered the same issue and could solve it by degrading the gym version. 
I saw gym==0.21.0 or the recent version raised the error, and then I degraded it to the older version, gym==0.10.0, in my case.
I think this error seems to be raised due to the change of the gym library.

**Comment by chenzhutian** [comment]
Wondering what if I want to use the gym with the latest's version

**Comment by Ahyuan233** [comment]
> Hi @naiyisiji, I'm not the author, but I had encountered the same issue and could solve it by degrading the gym version. I saw gym==0.21.0 or the recent version raised the error, and then I degraded it to the older version, gym==0.10.0, in my case. I think this error seems to be raised due to the change of the gym library.

You saved my day

**Comment by Tianci-Wen** [comment]
> Hi @naiyisiji, I'm not the author, but I had encountered the same issue and could solve it by degrading the gym version. I saw gym==0.21.0 or the recent version raised the error, and then I degraded it to the older version, gym==0.10.0, in my case. I think this error seems to be raised due to the change of the gym library.

Thank you very much! This is the correct solution.
