### ISSUE TITLE
The environment must specify an action space

### ISSUE THREAD

**Issue by MERONAL** [vita-epfl/CrowdNav#60]
Hi, I've managed to set up all the stuff but got the error message as below when I was running the train or test scripts:

```
Traceback (most recent call last):
  File "train.py", line 177, in <module>
    main()
  File "train.py", line 76, in main
    env = gym.make('CrowdSim-v0')
  File "/home/zy/miniconda3/envs/crowd_nav/lib/python3.6/site-packages/gym/envs/registration.py", line 669, in make
    env = PassiveEnvChecker(env)
  File "/home/zy/miniconda3/envs/crowd_nav/lib/python3.6/site-packages/gym/wrappers/env_checker.py", line 22, in __init__
    ), "The environment must specify an action space. https://www.gymlibrary.dev/content/environment_creation/"
AssertionError: The environment must specify an action space. https://www.gymlibrary.dev/content/environment_creation/

```

Any advice to fix this issue?

**Comment by ChanganVR** [comment]
@MERONAL it looks like gym version is not compatible, have you tried to downgrade the gym version to an older version? You can check out previous issues, which mentioned similar problems.

**Comment by MERONAL** [comment]
I reinstalled the environment and the issue is gone, not sure what happend thought. Thanks for your reply anyway.
