### ISSUE TITLE
Errors when using simulation environment

### ISSUE THREAD

**Issue by vietanhle-hri** [vita-epfl/CrowdNav#68]
I just tried running
```
python train.py --policy sarl
```
and see an error 
```
Traceback (most recent call last):
  File "train.py", line 177, in <module>
    main()
  File "train.py", line 76, in main
    env = gym.make('CrowdSim-v0')
  File "/home/vale/github/trajnet++/trajnetv/lib/python3.8/site-packages/gym/envs/registration.py", line 669, in make
    env = PassiveEnvChecker(env)
  File "/home/vale/github/trajnet++/trajnetv/lib/python3.8/site-packages/gym/wrappers/env_checker.py", line 20, in __init__
    assert hasattr(
AssertionError: The environment must specify an action space. https://www.gymlibrary.dev/content/environment_creation/
```
Can anyone help me to fix this?

**Comment by ChanganVR** [comment]
Please refer to this issue to solution: https://github.com/vita-epfl/CrowdNav/issues/65
