### ISSUE TITLE
Environment

### ISSUE THREAD

**Issue by liwenshulws** [vita-epfl/CrowdNav#70]
Hello, why am I running normally in Ubuntu 16.04 environment, but encountering an environment error in Ubuntu 20.04 environment? The error is as follows:
(base) ros2@ubuntu:~/CrowdNav/crowd_nav$ python train.py --policy sarl
Output directory already exists! Overwrite the folder? (y/n)y
2024-01-08 20:16:39, WARNING: Error getting git head hash code: Reference at 'refs/heads/master' does not exist
2024-01-08 20:16:39, INFO: Using device: cpu
2024-01-08 20:16:39, INFO: Policy: OM-SARL w/ global state
Traceback (most recent call last):
  File "train.py", line 183, in <module>
    main()
  File "train.py", line 82, in main
    env = gym.make('CrowdSim-v0')
  File "/home/ros2/miniconda3/lib/python3.8/site-packages/gym/envs/registration.py", line 669, in make
    env = PassiveEnvChecker(env)
  File "/home/ros2/miniconda3/lib/python3.8/site-packages/gym/wrappers/env_checker.py", line 20, in __init__
    assert hasattr(
AssertionError: The environment must specify an action space. https://www.gymlibrary.dev/content/environment_creation/
Could you please help me check if there is any urgency？

**Comment by ChanganVR** [comment]
Please refer to this solution: https://github.com/vita-epfl/CrowdNav/issues/65.
